name: Unit Test

on: push

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - run: python -m pip install .
      - run: python testserver.py | python test.py